on: [push, pull_request]

name: Test Coveralls

jobs:
  run:
    name: Node.js ${{ matrix.node }} @ ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [10, 12, 13]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: node --version
      - run: yarn --version

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test

      - name: Run Coveralls
        uses: coverallsapp/github-action@master
        if: startsWith(matrix.os, 'ubuntu') && matrix.node == 12
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
